### ISSUE TITLE
Error when parsing a "Zero-width no-break" space

### ISSUE THREAD

**Issue by gxxcastillo** [dcodeIO/Preprocessor.js#12]
I'm downloading a 3rd party file that has a "zero-width no-break" (U+FEFF) space in it and then running preprocess on it.  My preprocessor script looks something like this:

```
define(['jquery'], function ($) {
    /* @include path/to/my/file.js */
});
```

The resulting file ends up with an invalid character which then causes jshint (and buster-coverage) to puke :P

Would be great if preprocessor could recognize the zero-width no-break character and know what to do with it.

(I actually know next to nothing about this stuff but came across this as I was debugging some errors in the application I'm working on.  See http://en.wikipedia.org/wiki/Zero-width_no-break_space)

Thanks!

**Comment by dcodeIO** [comment]
Does jshint "puke" on the original file, too? If so, I am not sure if this is a task for preprocessor to take care of.

**Comment by gxxcastillo** [comment]
It actually doesn't.  The problem only comes up after running preprocess.

**Comment by gxxcastillo** [comment]
Sorry, I realize I have you in the dark here :P 

The problem is with the .js file from this library: https://github.com/briancherne/jquery-hoverIntent

If you run jshint on it after passing it through preprocess, you will get an "unsafe character" warning.

**Comment by gxxcastillo** [comment]
ugh, I'm a dork.  I'm actually using a different library with a very similar name (https://github.com/jsoverson/preprocess).  Apologies for the confusion :P
