### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by gamtiq** [dcodeIO/Preprocessor.js#14]
Link to documentation inside [Documentation](https://github.com/dcodeIO/Preprocessor.js#documentation) section of README is broken.

**Comment by tomByrer** [comment]
@gamtiq [test](https://github.com/tomByrer/Preprocessor.js/tree/patch-1#documentation) please?
edit: forgot patch-1

**Comment by gamtiq** [comment]
Link is correct in patch.
